class aa { constructor(a, b, d, e, f) { this.adomain = a; this.cid = b; this.crid = d; this.w = e; this.h = f } } class fa { constructor(a, b, d, e, f, g) { this.bid = a; this.render = b; this.ad = d; this.adComponents = e; this.allowComponentAuction = !0; this.bidCurrency = f; this.modelingSignals = g } } class ha { constructor(a) { this.debug_key = a } } class ia { constructor(a) { this.debugKey = a } } class x { constructor(a, b, d) { this.baseValue = a; this.scale = b; this.offset = d } } class y { constructor(a) { this.bucket = a; this.value = 1 } }
class D { constructor(a) { this.bucket = a; this.value = 1 } }; function ja(a) { if (void 0 !== a.q) { var b = ka(a, a.q); a.a.forDebuggingOnly.reportAdAuctionLoss(b.replace("{WON}", "false")); a.a.forDebuggingOnly.reportAdAuctionWin(b.replace("{WON}", "true")) } } function la(a, b) { a.e.w4 = void 0; a.e.w3 = void 0; a.e.w5 = b; ja(a) } function ma(a) { if (void 0 !== a.q) { var b = ka(a, a.q); a.a.forDebuggingOnly.reportAdAuctionLoss(b.replace("{WON}", "false")) } } function ka(a, b) { let d = JSON.stringify(a.e); return b.replace("{REPORT}", encodeURIComponent(d)).replace("{TBS}", a.J) }
class na { constructor(a, b) { this.a = a; this.h0 = { we: { z0: 0, z1: 0, z2: 0, z3: 0, z4: 0, z5: 0, z6: 0, z7: 0 }, wl: [], wd: {}, h4: { wg: 0, wh: 0, wj: 0 } }; this.h1 = { wa: 0, wb: 0, wc: 0, wd: {} }; this.J = ""; this.e = { h0: this.h0, h1: this.h1, w1: b } } }; const E = () => { }; function oa(...a) { console.log(a.map(b => "string" === typeof b ? b : JSON.stringify(b)).join(" ")) } class pa { constructor() { this.log = E } }; const F = [0, 1, 2, 3]; class qa { constructor(a, b, d, e, f, g, h, k) { this.status = a; this.c0 = b; this.c1 = d; this.c2 = e; this.c3 = f; this.j = g; this.reason = h; this.modelingSignals = k } }; class G { constructor(a, b, d, e, f) { this.status = a; this.c0 = b; this.j = d; this.modelingSignals = e; this.z = f } } class ra { constructor(a, b) { this.T = a; this.z = b } } class sa { constructor(a) { this.d = a } } class ta { constructor(a, b, d, e, f, g, h, k, l) { this.s8 = a; this.n4 = b; this.n2 = d; this.s9 = e; this.s2 = f; this.s1 = g; this.k = h; this.p = k; this.r5 = l } } class ua { constructor(a, b) { this.g = a; this.i = b } } class va { constructor(a, b) { var d = new pa; this.m = a; this.t = d; this.y = void 0; this.i5 = b } }; function J(a) { return 64 < a && 91 > a ? a - 65 : 96 < a && 123 > a ? a - 71 : 47 < a && 58 > a ? a + 4 : 43 === a ? 62 : 47 === a ? 63 : 0 }; function wa(a, b) { if (null === a || void 0 === a || 0 === a.length) return !0; const d = b.e10.split("x").map(Number); return null != a.find(e => { var f = d[0], g = d[1]; return f >= (e.p0 ?? 0) && g >= (e.p2 ?? 0) && f <= (e.p1 ?? Number.MAX_SAFE_INTEGER) && g <= (e.p3 ?? Number.MAX_SAFE_INTEGER) }) ? !0 : !1 }; function xa(a, b) { if (0 === b.e6) return !0; a = a.o6?.find(d => d.e5 === b.e5); return (a?.v2 ?? !1) && (a?.v1 ?? 2 === b.e6) }; class ya { a(a, b, d) { b = b.m.h1; let e = !1; for (const f of a) { e ? a = new G(1, 0, 0, 0, "dummy-fledge-skipped") : (a = new G(0, 0, 1E-4, 0, "dummy-fledge-picked"), e = !0); switch (a.status) { case 0: b.wc += 1; break; case 1: b.wa += 1; break; case 2: b.wb += 1 }d.H(f, a) } } }; function za(a) { return a.map(b => ({ value: b, I: Math.random() })).sort((b, d) => b.I - d.I).map(({ value: b }) => b) }; function Aa(a) { const b = Array(a.length); for (let d = 0; d < a.length; ++d)b[d] = K(a[d]); return b } function Ba(a) { const b = [4], d = Aa(a), e = b.reduce((g, h) => g * h), f = Array(e); for (let g = 0; g < e; ++g) { f[g] = 1; for (let h = 0; h < a.length; ++h)f[g] *= d[h][g] } return L(f, [e], b) } function Ca(a) { var b = [[2], [2]]; const d = Array(b.map(f => f[0]).reduce((f, g) => f + g)); let e = 0; for (let f = 0; f < b.length; ++f)for (let g = 0; g < b[f][0]; ++g)d[e] = a[f][g], ++e; return d; throw Error("Not implemented!"); }
function Da(a, b) { const d = (new Int32Array([236])).slice(); d[0] = 2; return L(a.slice(b, b + 2), d, d); throw Error("Should never happen; dim >= num_dims"); throw Error("Not implemented!"); } function L(a, b, d) { if (b.reduce((e, f) => e * f) !== d.reduce((e, f) => e * f)) throw Error("Total number of elements in input and output shapes do not match: " + JSON.stringify(b) + ";" + JSON.stringify(d)); a = K(a); for (b = d.length - 1; 0 <= b; --b)a = Ea(a, d[b]); return a[0] } function Ea(a, b) { let d = []; for (; 0 < a.length;)d.push(a.splice(0, b)); return d }
function K(a) { for ("number" === typeof a && (a = [a]); 0 < a.length && Array.isArray(a[0]);)a = [].concat(...a); 0 < a.length && ArrayBuffer.isView(a[0]) && (a = a.map(b => Array.from(b)), a = [].concat(...a)); ArrayBuffer.isView(a) && (a = Array.from(a)); return a } function Fa(a) { var b = [4]; const d = K(a); a = Array(b.reduce((e, f) => e * f) / b[0]); P(d, a, b, 0, Array(b.length), 0); b = b.slice(); b[0] = 1; return L(a, [a.length], b) }
function P(a, b, d, e, f, g) { if (g === d.length) { g = 0; for (var h = 0; h < d[e]; ++h)f[e] = h, g += a[Ga(d, f)]; b[Ha(d, f, e)] = g } else if (g === e) P(a, b, d, e, f, g + 1); else for (h = 0; h < d[g]; ++h)f[g] = h, P(a, b, d, e, f, g + 1) } function Ga(a, b) { let d = a.reduce((f, g) => f * g), e = 0; for (let f = 0; f < a.length; ++f)d /= a[f], e += b[f] * d; return e } function Ha(a, b, d) { let e = a.reduce((g, h) => g * h); e /= a[d]; let f = 0; for (let g = 0; g < d; ++g)e /= a[g], f += b[g] * e; for (d += 1; d < a.length; ++d)e /= a[d], f += b[d] * e; return f } var Ia = [1, 8, 32, 512]; function Ja(a, b = "") { a || console.log(b) }; class Ka { constructor(a) { this.a = a } }
class La {
    a(a, b, d) {
        if (void 0 === b.y) throw Error("Models evaluators not provided!"); const e = b.m.h1; b = new Ka(b.y); for (const v of za(a)) {
            let z; try {
                var f = v.i, g = b; a = f; var h = v.g; const H = a.k?.h1?.f1; if (void 0 === H) throw Error("missing requestTime in contextualSignals"); var k = g, l = a, n = H, m = {}; for (const c of F) { const B = k.a[c].D(l, n), A = k.a[c].C(B); m[c] = A } const S = a.s2; k = g; l = a; n = h; const T = {}; for (const c of F) { const B = k.a[c].l(l, n, m[c]); T[c] = B } k = m = T; l = {}; for (const c of F) l[c] = g.a[c].r(k[c]); g = l; if (0 === H % 2) {
                    const c =
                        m[0].v.concat([g[0], H]); Ja(236 === c.length, "Inconsistent bits extraction input size. Expected " + (236).toString() + " got " + c.length.toString()); const B = new Float32Array([c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7], c[8], c[9], c[10], c[11], c[12], c[13], c[14], c[15], c[16], c[17], c[18], c[19], c[20], c[21], c[22], c[23], c[24], c[25], c[26], c[27], c[28], c[29], c[30], c[31], c[32], c[33], c[34], c[35], c[36], c[37], c[38], c[39], c[40], c[41], c[42], c[43], c[44], c[45], c[46], c[47], c[48], c[49], c[50], c[51], c[52], c[53], c[54], c[55], c[56], c[57],
                        c[58], c[59], c[60], c[61], c[62], c[63], c[64], c[65], c[66], c[67], c[68], c[69], c[70], c[71], c[72], c[73], c[74], c[75], c[76], c[77], c[78], c[79], c[80], c[81], c[82], c[83], c[84], c[85], c[86], c[87], c[88], c[89], c[90], c[91], c[92], c[93], c[94], c[95], c[96], c[97], c[98], c[99], c[100], c[101], c[102], c[103], c[104], c[105], c[106], c[107], c[108], c[109], c[110], c[111], c[112], c[113], c[114], c[115], c[116], c[117], c[118], c[119], c[120], c[121], c[122], c[123], c[124], c[125], c[126], c[127], c[128], c[129], c[130], c[131], c[132], c[133], c[134], c[135],
                        c[136], c[137], c[138], c[139], c[140], c[141], c[142], c[143], c[144], c[145], c[146], c[147], c[148], c[149], c[150], c[151], c[152], c[153], c[154], c[155], c[156], c[157], c[158], c[159], c[160], c[161], c[162], c[163], c[164], c[165], c[166], c[167], c[168], c[169], c[170], c[171], c[172], c[173], c[174], c[175], c[176], c[177], c[178], c[179], c[180], c[181], c[182], c[183], c[184], c[185], c[186], c[187], c[188], c[189], c[190], c[191], c[192], c[193], c[194], c[195], c[196], c[197], c[198], c[199], c[200], c[201], c[202], c[203], c[204], c[205], c[206], c[207],
                        c[208], c[209], c[210], c[211], c[212], c[213], c[214], c[215], c[216], c[217], c[218], c[219], c[220], c[221], c[222], c[223], c[224], c[225], c[226], c[227], c[228], c[229], c[230], c[231], c[232], c[233], c[234], c[235]]); m = Array; var q = m.from; k = B; const A = Da(k, 2), ba = Da(k, 232), M = Ca([A, ba]), ca = JSON.parse(JSON.stringify(Ia)), Xa = Ba([ca, M]); var r = Fa(Xa); const da = q.call(m, r)[0]; Ja(0 <= da, "Bits reporting value should be >= 0"); Ja(4096 > da, "Bits reporting value should be < 2**12"); var p = da
                } else p = 4095; l = p; if (void 0 === S.h1) throw Error("missing userSignals.models");
                const I = a.s9.k3, N = (I?.d0 / 1E3 + g[0] * (I?.d1 + g[1] * (I?.d2 + g[2] * I?.d3))) * g[3] * S.h1.k1; m = I; k = g; var u = a.s9.f2; const [O, ea] = void 0 === m || null === m ? [2, 7] : void 0 === u || null === u ? [0, 8] : k[0] < (u.f3 ?? -Infinity) ? [1, 1] : k[0] > (u.f4 ?? Infinity) ? [1, 2] : k[1] < (u.f6 ?? -Infinity) ? [1, 3] : k[1] > (u.f7 ?? Infinity) ? [1, 4] : k[2] < (u.f8 ?? -Infinity) ? [1, 5] : k[2] > (u.f9 ?? Infinity) ? [1, 6] : [0, 0], C = new qa(O, g[0], g[1], g[2], g[3], N * I?.d4, ea, l), w = f.s9.k3, t = JSON.stringify({
                    c0: C.c0?.toExponential(6), c1: C.c1?.toExponential(6), c2: C.c2?.toExponential(6), c3: C.c3?.toExponential(4),
                    rr0: 222 * C.j, rr1: C.reason, d0: (333 * w?.d0)?.toExponential(4), d1: (444 * w?.d1)?.toExponential(4), d2: (555 * w?.d2)?.toExponential(4), d3: (666 * w?.d3)?.toExponential(4), k1: f.s2.h1.k1?.toExponential(3), d4: w?.d4?.toExponential(4)
                }); z = new G(C.status, C.c0, C.j, C.modelingSignals, t)
            } catch (H) { z = new G(2, 0, 0, 0, H.toString()) } switch (z.status) { case 0: e.wc += 1; break; case 1: e.wa += 1; break; case 2: e.wb += 1 }d.H(v, z)
        }
    }
}; class Ma { constructor(a, b, d) { this.o = a; this.j = b; this.modelingSignals = d } }
function Na(a, b, d) {
    var e; const f = b.m, g = []; Oa(a).forEach((k, l) => { k.T ? g.push(l) : f.h0.wl?.push({ s8: l.i.s8, o1: l.g.h0.o1, wk: `Not allowed:${k.z ?? ""}` }) }); f.h0.we.z2 = g.length; let h; 28837 === b.i5 || 28838 === b.i5 ? h = new ya : h = new La; h.a(g, b, { H: (k, l) => { if (0 === l.status) { const n = k.i.k.h0.e11; let m = l.j; m > n && (f.h0.we.z7 += 1, m = n); if (0 < m) { if (f.h0.we.z3 += 1, void 0 === e || m > e) d(new Ma(k, m, l.modelingSignals)), e = m } else f.h0.we.z4 += 1 } f.h0.wl?.push({ s8: k.i.s8, o1: k.g.h0.o1, wk: `Status:${l.status} m:${l.z ?? ""}` }) } }); b.t.log("[generateBid] perAdDebug = ",
        f.h0.wl, ", adsCounters = ", f.h0.we); void 0 === e && b.t.log(`None from ${a.length} ads were selected!`)
}
function Oa(a) {
    return new Map(a.map(b => {
        var d = b.g, e = b.i, f = e.k.h0; const g = xa(d.h0, f); var h = e.n4; var k = f.e1[h.l0.toString()]; h = h.l1; if (void 0 !== k) { var l = h >> 3; const q = Math.floor(l / 3) << 2; var n = J(k.charCodeAt(q + 3)); n |= J(k.charCodeAt(q + 2)) << 6; n |= J(k.charCodeAt(q + 1)) << 12; n |= J(k.charCodeAt(q)) << 18; k = 0 !== (n >>> 8 * (2 - l % 3) & 255 & 1 << (h & 7)) } else k = !1; h = d.h0.o4; l = f.e10; h = null === h || void 0 === h ? !0 : l === h; d = h && wa(d.h0.o3, f); if (!(h = null === e.n2 || null == f?.e2)) {
            h = e.n2; f = f.e2; e = e.p.d; if (null == e) var m = 0; else {
                f = f % 864E5 / 1E3; l =
                    0; for (m of e) m <= f && l++; m = l
            } h = h > m
        } m = h; return [b, new ra(g && k && d && m, (g ? "" : "R") + (k ? "" : "C") + (d ? "" : "S") + (m ? "" : "I"))]
    }))
}; const Pa = () => { }; function Qa(a, b) { let d = a.map(g => g.u1?.t1 ?? Ra); d = Sa(d); d = Ta(d); const e = 1 / Math.max(d.length - 1, 1), f = []; for (let g = 0; g < a.length; g++)f.push([a[g], d[g] + Ua * b * e * Va()]); Pa(f.slice(0, 10).map(g => g[1])); return f.sort(function (g, h) { return h[1] - g[1] }).map(g => g[0]) } function Sa(a) { var b = Ra, d = Wa; return a.map(e => Math.max(b, Math.min(e, d))) } function Ta(a) { const b = Math.min(...a); a = a.map(e => e - b); const d = Math.max(...a); 0 !== d && (a = a.map(e => e / d)); return a }
function Va() { let a = 0, b = 0; for (; 0 === a;)a = Math.random(); for (; 0 === b;)b = Math.random(); return Math.sqrt(-2 * Math.log(a)) * Math.cos(2 * Math.PI * b) } class Ya { sort(a, b) { const d = b.k?.h1?.f1; if (void 0 === d) throw Error("[chooser] missing requestTime in contextualSignals"); const e = (d - (b.s2?.h1?.k4 ?? -1)) / 1E3; b = b.p.d.filter(f => f <= e).length; return Qa(a, b) } } var Wa = 5, Ra = -5, Ua = 8; class Za { constructor(a, b) { this.K = a; this.W = b } } function $a(a, b, d) { d = d.m; b = b.s2.s3?.map(g => new Set(g.r0)) ?? []; const e = new Set(b.flatMap(g => g)), f = new Map; for (const g of a) d.h0.h4.wh += 1, a = b.map(h => h.has(g.a6)), a.some(h => h) && f.set(g.a6, new Za(g, a)); d.h0.h4.wj += e.size; d.h0.h4.wg += e.size - f.size; return f }
function ab(a, b, d) { const e = [], f = new Set; let g = !0; for (let h = 0; h < b.length && 20 > e.length; h++) { const k = b[h], l = Math.min(k.r1 ?? Number.MAX_SAFE_INTEGER, 20 - e.length); let n = 0; for (const m of a) { if (n === l) break; (d.get(m)?.W[h] ?? !1) && !f.has(m) && (f.add(m), e.push(m), n++) } if ((k.r2 ?? !1) && n < k.r0.length) { g = !1; break } } if (!g) throw Error("Not all obligatory offers were found in ad components"); return e }
function bb(a, b, d, e) { const f = d.s2.s3; if (null == f || 0 === f.length) return []; b = $a(b, d, e); e = Array.from(b.values()).map(g => g.K); a = a.a.sort(e, d).map(g => g.a6); if (e.length !== a.length) throw Error("offers sorter returned different number of ad components from what it received"); return ab(a, f, b) }
function cb(a, b) { if (0 === b.g.h0.o5) return null; if (0 === a.length) throw Error("choosingPhasesSignals must not be null or empty"); b = b.g.h0.o5; if (1 > b || 20 < b) throw Error(`adOffersNumber: "${b ?? ""}" must not be null and must be in range <1, 20>`); return a.slice(0, b) } class db { constructor() { this.a = new Ya } }; function Q(a) { a = encodeURIComponent(JSON.stringify(a ?? null)); return 5E3 >= a.length ? a : encodeURIComponent(JSON.stringify({ _rtbLengthError: a.substring(0, 5E3) })) } function R(a, b) { const d = a.split("?")[1].split("&").find(e => e.startsWith(b))?.substring(b.length); if (void 0 === d) throw Error(`Missing ${b} in ${a}`); return d }; const eb = {
    Q: "https://f.creativecdn.com", u: { M: "reserved.top_navigation_commit", render: "render", P: { Z: "reserved.top_navigation_start", debug: "debug" } }, N: "https://f.creativecdn.com/paapi-click?ctk={CTK}&asig={ASIG}&apsig={APSIG}&sspsig={SSPSIG}&dasig={DASIG}&env={ENV}&ap=web&iseid={ISEID}", X: "https://f.creativecdn.com/paapi-imp-delivery?ctk={CTK}&asig={ASIG}&apsig={APSIG}&sspsig={SSPSIG}&dasig={DASIG}&env={ENV}&ap=web&iseid={ISEID}", O: "https://f.creativecdn.com/fledge-ad-event-report?ctk={CTK}&type={TYPE}&asig={ASIG}&apsig={APSIG}&sspsig={SSPSIG}&dasig={DASIG}&env={ENV}&ap=web&iseid={ISEID}",
    L: "{OWNER}/fledge-biddebugreport?ctk={CTK}&won={WON}&report={REPORT}&tbs={TBS}&wb=${winningBid}&mwb=${madeWinningBid}&hsob=${highestScoringOtherBid}&mhsob=${madeHighestScoringOtherBid}&rr=${rejectReason}&asig={ASIG}&apsig={APSIG}&dasig={DASIG}&env={ENV}&ap=web", Y: "https://{DC}.creativecdn.com/paapi-win-notify?ctk={CTK}&asig={ASIG}&apsig={APSIG}&sspsig={SSPSIG}&dasig={DASIG}&env={ENV}&ap=web&iseid={ISEID}", V: (a, b) => `https://adscdn.com/creatives?id=${b}&c=${a}&s=rtbhfledge`, U: (a, b, d) => `https://adscdn.com/creatives?id=${b}&c=${a}&_oi=${d}&s=rtbhfledge`
}; function fb(a) { if (void 0 !== globalThis.privateAggregation?.enableDebugMode && null !== globalThis.privateAggregation?.enableDebugMode) { var b; "contributeToHistogram" in globalThis.privateAggregation ? b = new ia(a) : b = new ha(a); globalThis.privateAggregation.enableDebugMode(b) } }
function gb() {
    return {
        sendReportTo: globalThis.sendReportTo ?? (() => { }), privateAggregation: { contributeToHistogram: globalThis.privateAggregation?.contributeToHistogram ?? globalThis.privateAggregation?.sendHistogramReport ?? (() => { }), contributeToHistogramOnEvent: globalThis.privateAggregation?.contributeToHistogramOnEvent ?? globalThis.privateAggregation?.reportContributionForEvent ?? (() => { }), enableDebugMode: fb }, registerAdBeacon: globalThis.registerAdBeacon ?? (() => { }), forDebuggingOnly: globalThis.forDebuggingOnly ??
            { reportAdAuctionWin: () => { }, reportAdAuctionLoss: () => { } }, setBid: globalThis.setBid ?? (() => { })
    }
}; function hb(a) { a = a.exports.core_square; if ("function" !== typeof a) throw Error("wasmInstance.exports['core_square'] is not a function"); a = a(3); if (9 !== a) throw Error(`WASM function core_square returned wrong result: ${a} is not equal to 9`); }; function ib(a, b, d) { if (void 0 === b || null === b) throw Error(`${d} signals not provided!`); const e = b[a.a].b1; if (e !== a.b1) throw Error(`${d} signals incompatible with model version: ${String(e)} != ${a.b1}`); if (void 0 === b[a.a].v || null === b[a.a].v) throw Error(`${d} leg failure encountered!`); return b[a.a].v }
class jb { constructor(a, b, d, e, f, g, h) { this.s = a; this.b1 = b; this.n = d; this.c = e; this.f = f; this.b = h; this.a = kb[this.s] } D(a, b) { return this.c(a, b) } C(a) { return this.f(a) } r(a) { return this.b(a.v)[0] } l(a, b, d) { let e = []; for (const f of this.n) switch (f) { case "contextual": e = e.concat(ib(this, a.k.h1?.f0, f)); break; case "user_tag": e = e.concat(ib(this, a.s2.h1?.f0, f)); break; case "interest_based_bid": e = e.concat(ib(this, b.h1?.f0, f)); break; case "browser_signal": e = e.concat(d) }return { v: e } } }
const kb = { [0]: Object.keys({ c0: 0 })[0], [1]: Object.keys({ c1: 0 })[0], [2]: Object.keys({ c2: 0 })[0], [3]: Object.keys({ c3: 0 })[0] }; class lb extends jb { r(a) { const b = a.x; if (void 0 === b) throw Error("Missing AdditionalData in evaluateModelHead inputs"); a = this.b(a.v); return void 0 !== b.A ? Math.min(a[0], b.A) : a[0] } l(a, b, d) { b = super.l(a, b, d); d = {}; a = a.s2?.h1?.k5; !0 === a?.j0 && (d.A = a.j2); b.x = d; return b } }; class mb extends jb { r(a) { const b = a.x; if (void 0 === b) throw Error("Missing AdditionalData in evaluateModelHead inputs"); return void 0 !== b.B ? b.B : this.b(a.v)[0] } l(a, b, d) { b = super.l(a, b, d); d = {}; a = a.s2?.h1?.k5; !0 === a?.j1 && (d.B = a.j3); b.x = d; return b } }; class nb { D() { return [] } C() { return [] } l(a) { a = a.k?.h1?.f0?.c3?.v; if (void 0 === a || null === a) throw Error("Missing PO value in contextual signals"); return { v: a } } r(a) { return a.v?.[0] } }; function ob(a) { return a.offset + a.length } class U { constructor(a) { this.length = a; this.offset = 0 } } function pb(a) { switch (a) { case 0: return new U(3E5); case 1: return new U(12E5); case 2: return new U(18E5); case 3: return new U(36E5); case 4: return new U(54E5); case 5: return new U(108E5); case 6: return new U(216E5); case 7: return new U(864E5); case 8: return new U(2592E5); case 9: return new U(6048E5) } }; function qb(a) { return a.b.map(b => Number(b ? 1 : 0)).reduce((b, d) => b + d) } class rb { constructor(a) { this.a = this.c = 0x7fffffffffffffff; this.b = Array.from({ length: 7 }, () => !1); this.f = a - 864E5 * Math.floor(a / 864E5) } } function sb(a, b) { if (!(b < a.c)) { b -= a.c; 0 > a.b && (a.b = b); a.b = Math.min(a.b, b); for (var d = 0; 10 > d && b > ob(a.n[d]);)d++; 10 > d && a.a[d]++ } } function tb(a) { for (let b = 1; 10 > b; b++)a.a[b] += a.a[b - 1] }
class ub { constructor(a) { this.f = -1; this.n = Array.from({ length: 10 }, (b, d) => pb(d)); this.b = this.f; this.a = Array.from({ length: 10 }, () => 0); this.c = a } } function vb(a, b) { b.forEach(d => { var e = a.c; const f = Math.floor((d - e.f) / 864E5) + 1; 1 <= f && 8 > f && (e.a = Math.min(e.a, f), e.b[f - 1] = !0); sb(a.a, d); sb(a.b, d) }); tb(a.a); tb(a.b) } class wb { constructor(a, b) { this.c = new rb(a); this.a = new ub(0); this.b = new ub(Math.max(a - b)) } }; function xb(a, b, d) { a = new wb(a, b); vb(a, d); return [a.a.a[0], a.a.a[2], a.a.a[4], a.a.a[6], a.a.a[9], a.b.a[2], a.b.a[7], a.b.a[9], a.c.a, qb(a.c), 0 > a.a.b ? NaN : a.a.b / 1E3] } function yb(a, b) { const d = a.s2?.h1?.k4 ?? -1; a = a.p?.d?.map(e => 1E3 * e) ?? []; return [(b - d) / 6E4].concat(xb(b, d, a)) }; var zb = ["browser_signal", "contextual", "interest_based_bid", "user_tag"], Ab = { browser_signal: 4, contextual: 200, interest_based_bid: 10, user_tag: 20 }; function Bb(a, b, d) { a = new wb(a, b); vb(a, d); return [qb(a.c), a.a.a[7], a.a.a[8], a.a.a[9], a.b.a[7], a.b.a[8], a.b.a[9]] } function Cb(a, b) { const d = a.s2?.h1?.k4 ?? -1; a = a.p?.d?.map(e => 1E3 * e) ?? []; return [(b - d) / 6E4].concat(Bb(b, d, a)) }; var Db = ["contextual", "user_tag", "browser_signal", "interest_based_bid"], Eb = { contextual: 7, user_tag: 107, browser_signal: 7, interest_based_bid: 2 }; function Fb(a, b) { return [(b - (a.s2?.h1?.k4 ?? -1)) / 864E5] }; var Gb = ["user_tag", "contextual", "browser_signal"], Hb = { user_tag: 1, contextual: 1, browser_signal: 1 }; function Ib(a) {
    return {
        [0]: new jb(0, "6dc78ecb_77", zb, yb, b => { var d = Array, e = d.from; const f = new Float32Array(4); for (let g = 0; 12 > g; ++g)a.exports.ab6dc78ecb_77(g, b[g]); a.exports.db6dc78ecb_77(); for (b = 0; 4 > b; ++b)f[b] = a.exports.cb6dc78ecb_77(b); return e.call(d, f) }, Ab, b => { var d = Array, e = d.from; const f = new Float32Array(1); for (let g = 0; 234 > g; ++g)a.exports.ac6dc78ecb_77(g, b[g]); a.exports.dc6dc78ecb_77(); for (b = 0; 1 > b; ++b)f[b] = a.exports.cc6dc78ecb_77(b); return e.call(d, f) }), [1]: new lb(1, "15f9cad2_41", Db, Cb, b => {
            var d =
                Array, e = d.from; const f = new Float32Array(7); for (let g = 0; 8 > g; ++g)a.exports.ab15f9cad2_41(g, b[g]); a.exports.db15f9cad2_41(); for (b = 0; 7 > b; ++b)f[b] = a.exports.cb15f9cad2_41(b); return e.call(d, f)
        }, Eb, b => { var d = Array, e = d.from; const f = new Float32Array(1); for (let g = 0; 123 > g; ++g)a.exports.ac15f9cad2_41(g, b[g]); a.exports.dc15f9cad2_41(); for (b = 0; 1 > b; ++b)f[b] = a.exports.cc15f9cad2_41(b); return e.call(d, f) }), [2]: new mb(2, "e82d993f_43", Gb, Fb, b => {
            var d = Array, e = d.from; const f = new Float32Array(1); for (let g = 0; 1 > g; ++g)a.exports.abe82d993f_43(g,
                b[g]); a.exports.dbe82d993f_43(); for (b = 0; 1 > b; ++b)f[b] = a.exports.cbe82d993f_43(b); return e.call(d, f)
        }, Hb, b => { var d = Array, e = d.from; const f = new Float32Array(1); for (let g = 0; 3 > g; ++g)a.exports.ace82d993f_43(g, b[g]); a.exports.dce82d993f_43(); for (b = 0; 1 > b; ++b)f[b] = a.exports.cce82d993f_43(b); return e.call(d, f) }), [3]: new nb
    }
}; class V { constructor(a, b) { this.R = a; this.S = b } }
function Jb(a, b) {
    b = BigInt(W(b)); const d = [new V("reserved.win", new y(32n * b + 2n)), new V("imp", new y(32n * b + 3n)), new V("click", new y(32n * b + 4n)), new V("reserved.win", new y(137438953474n)), new V("imp", new y(137438953475n)), new V("click", new y(137438953476n))]; a && (d.push(new V("reserved.loss", new D(new x("bid-reject-reason", 1, 32n * b + 16n)))), d.push(new V("reserved.win", new y(137438953477n)), new V("reserved.loss", new y(137438953478n)), new V("reserved.always", new y(137438953479n))), d.push(new V("reserved.loss",
        new D(new x("bid-reject-reason", 1, 137438953480n)))), d.push(new V("reserved.always", new D(new x("script-run-time", .1, 137438953496n))), new V("reserved.always", new D(new x("script-run-time", .1, 137439193496n + 240000n * b)))), d.push(new V("reserved.always", new D(new x("signals-fetch-time", .1, 137439013496n))), new V("reserved.always", new D(new x("signals-fetch-time", .1, 240000n * b + 137439253496n))))); d.push(new V("reserved.win", new D(new x("script-run-time", .1, 137439073496n))), new V("reserved.win", new D(new x("script-run-time",
            .1, 240000n * b + 137439313496n)))); d.push(new V("reserved.win", new D(new x("signals-fetch-time", .1, 137439133496n))), new V("reserved.win", new D(new x("signals-fetch-time", .1, 240000n * b + 137439373496n)))); return d
} function W(a) { var b = 0; if (void 0 === a || 0 === a?.length) return b; for (let d = 0; d < a.length; d++)b = (b << 5) - b + a.charCodeAt(d), b |= 0; return Math.abs(b) }; class Kb { constructor() { this.a = eb } 
generateBid(a, b, d, e, f, g) { const h = gb(), k = new va(new na(h, a.name), b?.i5 ?? void 0); try { return Lb(a, b, d, e, f, g, h, k, this.a, "ondevice") } catch (l) { return X(k, 3, l.stack.substring(0, 256)) } }
reportWin(a, b, d, e, f) { Mb(a, b, d, e, f, gb(), this.a, "ondevice") } } function Y(a) { throw Error(a); }

function Lb(a, b, d, e, f, g, h, k, l, n) {
    b = Object.assign({}, b ?? {}, d?.h2?.g2 ?? {}); const m = k.t; b.i1 ?? !1 ? m.log = oa : m.log = E; m.log("[generateBid] arguments=", arguments); var q = 1 === W((d?.h2?.g1 ?? "") + a.name) % 100, r = q ? [new y(32n * BigInt(W(a.name)) + 1n), new y(137438953473n)] : []; q = Jb(q, a.name); Nb(h, d, r, q); const p = k.m; p.h1.i5 = k.i5; if (null === d) return X(k, 8); if (!1 !== b.i3) {
        r = Q(b); q = Q(Object.assign({}, f, { prevWins: void 0, prevWinsMs: void 0, wasmHelper: void 0 })); var u = Q(g?.auctionSignals); r = l.L.replace("{OWNER}", a?.owner ?? l.Q).replace("{CTK}",
            d.h0.e12).replace("{ASIG}", r).replace("{APSIG}", q).replace("{DASIG}", u).replace("{ENV}", n); null !== r && void 0 !== r && (p.q = r, p.e.w4 = 1, p.e.w3 = void 0, ma(p))
    } if (null === e) return X(k, 11); if (1 !== Object.keys(e).length) throw Error("Invalid trustedBiddingSignals provided! Keys: " + JSON.stringify(Object.keys(e))); r = Object.keys(e).find(t => null !== t && void 0 !== t) ?? ""; p.J = r; r = Object.values(e).find(t => null !== t && void 0 !== t); if (null === r || void 0 === r) return X(k, 6); if (1 === r.s6) return X(k, 12); q = r.s5; if (null === q || void 0 === q) return X(k,
        5); if (void 0 === f.wasmHelper) return X(k, 9); u = new WebAssembly.Instance(f.wasmHelper); hb(u); k.y = Ib(u); const v = "tee" === n ? new Ob(f, q, l) : new Pb(a, f, q), z = v.G(), H = v.F(), S = v.n(); u = Qb(q, d, v.s()); const T = new db, I = new Map(u.map(t => { const c = void 0 !== H ? H.get(t.s8) ?? new Map : void 0, B = S.get(t.s8) ?? []; return [t.s8, bb(T, B.filter(A => c?.has(A.a6) ?? !0), t, k)] })), N = 1E3 * (d.h0.e9 ?? Number.NEGATIVE_INFINITY), O = ("USD" === b?.prebid?.bidfloorcur ? b?.prebid?.bidfloor : null) ?? Number.NEGATIVE_INFINITY; q = u.flatMap(t => {
            const c = void 0 !==
                z ? z.get(t.s8) ?? new Map : void 0, B = I.get(t.s8)?.length ?? 0; return t.s1.filter(A => c?.has(A.h0.o1) ?? !0).filter(A => B >= A.h0.o5).map(A => new ua(A, t))
        }); p.h0.h3 = d.h3; p.h0.g3 = d.h2?.g3; p.h0.s4 = r.s4; p.h0.we.z0 = !("ads" in a) || "adRenderIds" in a ? null : a.ads.length; p.h0.we.z1 = u.reduce((t, c) => t + c.s1.length, 0); p.h0.we.z5 = u.length; r = d.h0.e10.split("x").map(Number); const ea = r[0], C = r[1]; let w; Na(q, k, t => {
            const c = t.o.i.s8, B = t.o.g.h0.o1, A = 1E3 * t.j, ba = v.f(c, B) ?? Y("Invalid creativeHash returned from auction!"); var M = I.get(c) ??
                []; M = cb(M, t.o)?.map(ca => v.c(c, ca) ?? Y("Invalid offerId returned from auction!")); w = new fa(A, ba, new aa([t.o.i.r5], c, `${B}_${c}`, ea, C), M, "USD", t.modelingSignals); b?.i4?.includes("setBid") ?? !1 ? m.log("[generateBid] setBid skipping - api is disabled") : N > w.bid ? m.log(`[generateBid] Bid ${w.bid} is lower than contextual floor ${N}`) : O > w.bid ? m.log(`[generateBid] Bid ${w.bid} is lower than fledge auction dedicated floor ${O}`) : (h.setBid(w), p.h0.we.z6 += 1, p.e.w5 = w, ja(p))
        }); if (void 0 === w) return X(k, 7); if (N > w.bid) return X(k,
            10); if (O > w.bid) return X(k, 4); la(p, w); m.log("[generateBid] result=", w); return w
}
function Mb(a, b, d, e, f, g, h, k) {
    var l = Object.assign({}, a ?? {}, b?.h2?.g2 ?? {}), n = new pa; l.i1 ?? !1 ? n.log = oa : n.log = E; n.log("[reportWin] arguments=", arguments); null === b && Y("Missing contextual signals"); n = Q(l); const m = Q(d), q = Q(e), r = Q(f?.auctionSignals); var p = e.bid; l = R(e.renderUrl, "c="); const u = R(e.renderUrl, "id="); var v = []; for (var z = 0; 48 > z; z++).5 > Math.random() ? v.push("0") : v.push("1"); v = BigInt("0b" + v.join("")).toString(); z = b.h0.e12; p = Rb(h, z, n, q, m, r, k, v, p, l, u); g.registerAdBeacon(p); n = h.Y.replace("{DC}", b.h3?.x0 ??
        "").replace("{CTK}", z).replace("{ASIG}", n).replace("{APSIG}", q).replace("{SSPSIG}", m).replace("{DASIG}", r).replace("{ENV}", k).replace("{ISEID}", v); g.sendReportTo(n); Nb(g, b, [new y(32n * BigInt(W(l))), new y(137438953472n)], [])
}
function Rb(a, b, d, e, f, g, h, k, l, n, m) { function q(u) { return u.replace("{CTK}", b).replace("{ASIG}", d).replace("{APSIG}", e).replace("{SSPSIG}", f).replace("{DASIG}", g).replace("{ENV}", h).replace("{ISEID}", k).replace("{BID}", `${l}`).replace("{C}", n).replace("{ID}", m) } const r = a.O; var p = a.u.P; p = void 0 !== r && void 0 !== p ? Object.fromEntries(Object.entries(p).map(([u, v]) => [v, q(r.replace("{TYPE}", u))])) : {}; return { [a.u.M]: q(a.N), [a.u.render]: q(a.X), ...p } }
function Qb(a, b, d) { return a.map(e => { const f = e.s8, g = new sa(d.get(f) ?? []); return new ta(f, e.n4, e.n2 ?? null, e.s9, e.s2, e.s1, b, g, e.r5) }) } function X(a, b, d) { a.t.log("[generateBid] error", b, d); a = a.m; a.e.w4 = b; a.e.w3 = d; ma(a); return new fa(0, "", null) } function Nb(a, b, d, e) { a.privateAggregation.enableDebugMode(BigInt(W(b?.h2?.g1 ?? ""))); for (const f of d) a.privateAggregation.contributeToHistogram(f); for (const f of e) a.privateAggregation.contributeToHistogramOnEvent(f.R, f.S) }
class Pb {
    constructor(a, b, d) {
        this.b = new Map; this.a = new Map; this.r4 = new Map; this.d = new Map; a.ads.forEach(e => { const f = R(e.renderUrl, "c="), g = e.metadata.o1, h = this.b.get(f) ?? new Map; h.set(g, e.renderUrl); this.b.set(f, h) }); a.adComponents?.forEach(e => { const f = R(e.renderUrl, "c="), g = R(e.renderUrl, "_oi="); var h = this.a.get(f) ?? new Map; h.set(g, e.renderUrl); this.a.set(f, h); h = this.r4.get(f) ?? []; h.push({ a6: g, u1: e.metadata.u1 }); this.r4.set(f, h) }); d.forEach(e => { this.d.set(e.s8, e.s2.h1.j4?.j5 ?? []) }); b.prevWins?.forEach(([e,
            f]) => { f = f.render_url ?? Y("Expected render_url in prevWins"); f = R(f, "c="); this.d.get(f)?.push(e) })
    } f(a, b) { return this.b.get(a)?.get(b) } c(a, b) { return this.a.get(a)?.get(b) } G() { return this.b } F() { return this.a } n() { return this.r4 } s() { return this.d }
}
class Ob {
    constructor(a, b, d) { this.a = d; this.b = new Map; this.r4 = new Map; this.d = new Map; const e = new Map; b.forEach(f => { const g = f.s8, h = f.s2.h1.j4?.j5 ?? [], k = f.s1[0]?.h0.o7 ?? Y("Campaign with no adRenderId"); e.set(k.slice(0, k.length / 2), h); this.d.set(g, h); void 0 !== f.r3 && null !== f.r3 && (this.b.set(g, f.r3), this.r4.set(g, f.s2.r4 ?? [])) }); a.prevWins?.forEach(([f, g]) => { g = "string" === typeof g ? g : Y("Expected adRenderId in prevWins"); e.get(g.slice(0, g.length / 2))?.push(f) }) } f(a, b) { return this.a.V(a, b) } c(a, b) {
        const d = this.b.get(a) ??
            Y("Missing productCreativeHash"); return this.a.U(a, d, b)
    } G() { } F() { } n() { return this.r4 } s() { return this.d }
}; const Z = new Kb; globalThis.generateBid = Z.generateBid.bind(Z); globalThis.reportWin = Z.reportWin.bind(Z);